//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZariTouDM
    {
        public int NumberOfRoll { get; set; }
        public int RollDice { get; set; }
        public string Buff { get; set; }
        public string Debuff { get; set; }
    }
}
